import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBAr from "./navComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SMCT Event",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBAr />
        {children}
        <script>
          console.log("%cWelcome to SMCT Event!","font-family: Courier New,
          Courier, monospace; color: #00ff00; background: #000; text-shadow: 0 0
          5px #00ff00; font-size: 20px;");
        </script>
      </body>
    </html>
  );
}
